# Generated by Django 6.0.4 on 2026-05-11 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_created_at_alter_user_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('current_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('targeted_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('activity_level', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_goal', models.CharField(blank=True, max_length=50, null=True)),
                ('daily_calorie_target', models.IntegerField(blank=True, null=True)),
                ('health_issues', models.TextField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('dietary_preference', models.CharField(blank=True, max_length=50, null=True)),
                ('meal_intake_per_day', models.IntegerField(blank=True, null=True)),
                ('water_intake_litres', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('sleep_schedule', models.CharField(blank=True, max_length=100, null=True)),
                ('regional_culture', models.CharField(blank=True, max_length=100, null=True)),
                ('available_cooking_time', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_cooking_oil', models.CharField(blank=True, max_length=100, null=True)),
                ('grocery_budget', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_meal_location', models.CharField(blank=True, max_length=100, null=True)),
                ('main_carbs_source', models.CharField(blank=True, max_length=100, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_photo_url', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
