# Generated by Django 6.0.5 on 2026-05-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userprofile_bmi_userprofile_disliked_foods_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
