# Generated by Django 6.0.5 on 2026-05-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_otp_user_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_onboarded',
            field=models.BooleanField(default=False),
        ),
    ]
