# Generated by Django 6.0.4 on 2026-05-16 19:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_otp_user_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='day_of_birth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='daily_tracking',
            fields=[
                ('tracking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_calories_consumed', models.IntegerField(blank=True, null=True)),
                ('total_carbs', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_fat', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('water_intake_liters', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('junk_score_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('surplus_or_deficit', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('behaviour_summary', models.CharField(max_length=100)),
                ('meal_count', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_tracking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='meal_logs',
            fields=[
                ('meal_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meal_type', models.CharField(blank=True, max_length=50, null=True)),
                ('meal_location', models.CharField(blank=True, max_length=100, null=True)),
                ('meal_timedate', models.DateTimeField(auto_now_add=True)),
                ('detected_items', models.CharField(blank=True, max_length=100, null=True)),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('protein_gm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('carbs_gm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fat_gm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('junk_score', models.IntegerField(blank=True, null=True)),
                ('ai_insights', models.CharField(blank=True, max_length=100, null=True)),
                ('meal_photo_url', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('tracking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_logs', to='api.daily_tracking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
