# Generated by Django 6.0.4 on 2026-05-21 15:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userprofile_day_of_birth_daily_tracking_meal_logs'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat_logs',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(default='text', max_length=50)),
                ('user_message', models.TextField(blank=True, null=True)),
                ('ai_response', models.TextField(blank=True, null=True)),
                ('behaviour_summary', models.TextField(blank=True, null=True)),
                ('meal_context', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('audio_file_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
