# Generated by Django 6.0.4 on 2026-05-23 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userprofile_is_onboarded'),
        ('api', '0008_chat_logs'),
    ]

    operations = [
    ]
